### ISSUE TITLE
Don't be a pain in the ass for node community

### ISSUE THREAD

**Issue by broofa** [broofa/node-mime#108]
All, I've been a bit of an absentee landlord as far as maintaining this library goes. My response time on issues has been horrid, and that https://github.com/jshttp/mime-types exists is testament to the poor job I've been doing.  For this I humbly apologize.

Moving forward, I'd like to insure this isn't an issue.  So... What's the right thing to do here? Are there parties interested in being added as maintainers?  (If so, who?)  Should this library be deprecated in favor of mime-types? Could mime-types be pulled in here?

Hopefully I haven't completely alienated everyone.  I'm genuinely interested in hearing everyone's opinions, and willing to do whatever the community thinks is best. 

cc: @dominictarr @Fishrock123 @substack @jonathanong

**Comment by Hypercubed** [comment]
I'm interested (and created: https://github.com/Hypercubed/node-mime) a library that can do this:

```
var MimeLookup = require('mime');
var mime = new MimeLookup({ /* my own definitions */ });
```

https://github.com/jshttp/mime-types cannot do that and has `mime-db` as a dependency.  My proposal is to split the module into two parts (see #129).

**Comment by Hypercubed** [comment]
FYI: https://github.com/Hypercubed/mime-lookup

**Comment by docunext** [comment]
Why do you, @broofa, have to be the only author of `node-mime`? I find the points presented by @Fishrock123 and @dougwilson to be surprisingly level-headed, specifically the point that multiple mime libraries can happily co-exist.

Anwyay, I'm glad I stopped by `mime-types` looks to be what we needed with the PR @loudwinston made in https://github.com/broofa/node-mime/pull/136

**Comment by Hypercubed** [comment]
@docunext I'm not sure what you mean by valves.  My proposal in #129 was to separate the lookup API from the mime-db itself, it had nothing to do with adding types.  The mime-db large.  If I use node-mime in the browser, and I did for some time, it to too much to send over the wire.  https://github.com/Hypercubed/mime-lookup is a fork of node-mime that provides just the API.  The database can be then entire mime-db (https://github.com/Hypercubed/mime-lookup#using-mime-db) or a subset as I have done here: https://github.com/Hypercubed/Project-Chi/blob/master/app/common/services/datapackage/mime.js

**Comment by broofa** [comment]
Hey all, thanks for the comments and, more importantly, your patience.

@docunext - I don't have to be the only contributor to this repository.  It's more that there's never really been an obvious person to hand responsibility off to.  I'm open to suggestions, especially if you have someone in mind who has a demonstrated ability to responsibly shepard a library that a lot of projects depend on.

**Comment by Hypercubed** [comment]
Hello @broofa,

is the difficulty maintaining the mime database or the repo itself.  I think my proposal in #129 could help.

**Comment by broofa** [comment]
Closing this out as node-mime is sits on mime-db now.
