### ISSUE TITLE
Consider adding support for hjson.

### ISSUE THREAD

**Issue by howardroark** [broofa/node-mime#110]
I'm going to delete the fork I have setup. That may close the pull request automatically.  Let's consider this issue a place holder for the conversation.

Project link: http://laktak.github.io/hjson/
Mime type: text/hjson
File extension: hjson

Cross referencing some concerns:
https://github.com/laktak/hjson/issues/12

Thanks!

**Comment by broofa** [comment]
node-mime now sits on top of https://github.com/jshttp/mime-db.  Please submit requests for new types there.  Thanks!
