### ISSUE TITLE
Extensionless paths should return null or false

### ISSUE THREAD

**Issue by huyinghuan** [broofa/node-mime#113]
In general,  

```
mime.lookup('/path/to/file.css');  // ==>  text/css   the result is ok
mime.lookup('file.css'); // ==>  text/css   the result is ok
mime.lookup('.css'); // ==>  text/css   the result is ok
mime.lookup('css'); // ==>  text/css   the result is ok
//but
mime.lookup('path/to/css');  // ==>  text/css  . the result is　controversial
```

**Comment by broofa** [comment]
What do you suggest the behavior should be?

**Comment by huyinghuan** [comment]
I think it should be default value ```application/octet-stream``` when the parameter is a file path and it have not extension name.

**Comment by gsf** [comment]
I just ran into this issue with a path like `/admin/new/text` that I expected to be application/octet-stream instead of text/plain.

**Comment by dougwilson** [comment]
The `mime-types` library, a similar library to this one, also had the same issue. If someone wants to copy/view our fix to incorporate here: https://github.com/jshttp/mime-types/commit/f5e2eb2c4e005a8287a0d9892c9543449d884bb1

**Comment by broofa** [comment]
Fixed in `v2`
