### ISSUE TITLE
Add common name?

### ISSUE THREAD

**Issue by metaraine** [broofa/node-mime#114]
Thoughts about adding a property like `commonName` that provides a short, commonly used label for certain types?

e.g.
text/calendar is commonly known as iCalendar.

This is coming up for me because I am building an app that displays file types as a dropdown list for end users.

**Comment by broofa** [comment]
Hi Raine, I can see how this would be valuable, but it's out of scope for this project.  (And will be even more out of scope once I finish merge the PR I have up for switching over to use `mime-db` as the source of mime mappings.)

One issue I see with this is that not only are there 100's of mime-types that you'd need to determine the common names for, but users will likely contest some of the naming.  And at some point you'd probably need to worry about localization issues.   So, not a small problem.

**Comment by metaraine** [comment]
Most mime-types can just use what's after the `/`, without `x-` or `vnd`, as a user-friendly name. There were just a few like iCalendar that are different and indeterminable from the type alone. Localization is certainly out of scope.

I will see what the folks over at `mime-db` have to say. Thanks for the response!
