### ISSUE TITLE
.wav files show up as "audio/x-wav" instead of "audio/x-wave"

### ISSUE THREAD

**Issue by LorenzGardner** [broofa/node-mime#118]
when setting the mime type for .wav files internet explore is a bit picky...

valid options are:  audio/wav, audio/wave, audio/x-wave, audio/vnd.wave

Chrome happily accepts the "audio/x-wav" but IE does not.

**Comment by broofa** [comment]
Can you file this with the  https://github.com/jshttp/mime-db project? That's where node-mime's extension->mime type maps come from these days.

Before you do, though, can you check to see if using `audio/wav` produces consistent behavior across browsers?  That's the official type as per [the IANA Waveform Audio File Format registration](http://tools.ietf.org/html/draft-ema-vpim-wav-00).

Thanks!

**Comment by LorenzGardner** [comment]
Yes that works for Chrome and I.E

No idea about fire fox, Opera, ect ...

**Comment by broofa** [comment]
See #160
