### ISSUE TITLE
Feature: support for expanding MIME patterns

### ISSUE THREAD

**Issue by IvanGoncharov** [broofa/node-mime#121]
In some protocols(Google Discovery in my case) MIME globing patterns is used.
I implement function that do expansion of such patterns:
>"\*/\*" => ["application/octet-stream"]
>"video/*"=> [ "video/1d-interleaved-parityfec", "video/3gpp", ...]

I want create PR with these feature.
Do you interested in adding such feature?

**Comment by broofa** [comment]
I'm not sure what you're asking for.  Can you elaborate?

**Comment by IvanGoncharov** [comment]
A PR is worth a thousands words.
So I create #122 
After some research I even found [spec](http://tools.ietf.org/html/rfc2616#section-14.1) describing this feature.

**Comment by IvanGoncharov** [comment]
PR was merged into https://github.com/Hypercubed/mime-lookup
