### ISSUE TITLE
how does .types file format look like?

### ISSUE THREAD

**Issue by dotnetCarpenter** [broofa/node-mime#123]
The [README.md](../blob/master/README.md) says:
> The .types file format is simple - See the types dir for examples.

But there is no `types` directory.
To my surprise, I couldn't find an example via google...

**Comment by broofa** [comment]
Sorry, the docs are out of date.  node-mime no longer provides it's own types database. Instead, it relies on the https://github.com/jshttp/mime-db project.  Have a look at the Apache [mime.types file](https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x/conf/mime.types) for an example.
