### ISSUE TITLE
how to support plist？

### ISSUE THREAD

**Issue by luobaoan** [broofa/node-mime#126]
how to support plist？

**Comment by broofa** [comment]
Sorry, I don't understand what you are asking.  Can you be more specific?

**Comment by luobaoan** [comment]
Thank you for your help!
My project in xampp is ok,but in gulp-connect when it preload *.plist will stop…… my project is cocos2d-js

**Comment by broofa** [comment]
Sorry, I still don't understand.  Are you asking node-mime to accept plist-formatted mime type definitions?  If so, I don't plan on supporting that any time soon.  I'm actually moving away from working with type definition files directly, in preference for getting mime types from the mime-db project.
