### ISSUE TITLE
requested features

### ISSUE THREAD

**Issue by Somebi** [broofa/node-mime#131]
Removing default octet mime type would be better... Just null would be nice.

And passing req.url with query parameters not working, only parsing url and passing parsed.pathname works. Would be nice to pass raw req.url and it gives proper mime.

**Comment by Somebi** [comment]
here:
https://github.com/broofa/node-mime/blob/master/mime.js#L69
```javascript
var results=path.match(/\.([a-z]+).*$/i);
if(results!==null && results[1]) {
var ext=results[1];
}
else {
return fallback || this.default_type;
}

return this.types[ext];

```

**Comment by Somebi** [comment]
Regexp should be tested though.

**Comment by broofa** [comment]
Re: default type, see #139.
Re: urls, I'm not a big fan of overloading method arguments (allowing 
 String or Url), and would prefer not to add another method for this. 
 So, for now, I'm okay leaving this as a problem for the caller. `mime.lookup(req.url.replace(/\?.*/,''))` works.
