### ISSUE TITLE
Directories should appear as something other than application/octet-stream

### ISSUE THREAD

**Issue by watzon** [broofa/node-mime#135]
There is a depreciated definition for a mime type of text/directory which could be used if there aren't any other ideas. I feel like it would be a good idea to have something other than application/octet-stream since there will be times when a user want's to differentiate between a directory and a binary file.

**Comment by broofa** [comment]
Doing a bit of issue housekeeping.  This module doesn't do filesystem stat'ing (and won't anytime soon), so no way to know if a path is a directory or not.  But, agreed that application/octet-stream probably shouldn't be the default.  See #139.
