### ISSUE TITLE
charsets image/png undefined

### ISSUE THREAD

**Issue by whitecolor** [broofa/node-mime#140]
is it ok that 
```javascript
mime.charsets.lookup(mime.lookup('.png')) === undefined
```
?

**Comment by broofa** [comment]
I believe `charset` is only meaningful for `text/*` mime types.  PNG mime type is `image/png`; hence, no charset.
https://tools.ietf.org/html/rfc6657

**Comment by whitecolor** [comment]
Ok, thanks for pointing)
