### ISSUE TITLE
Dynamic adaptive streaming over HTTP (DASH) file extension typo

### ISSUE THREAD

**Issue by mruddy** [broofa/node-mime#141]
https://www.iana.org/assignments/media-types/application/dash+xml

application/dash+xml is registered for file extension "mpd", not "mdp" as was pulled from https://github.com/broofa/node-mime/pull/59

related standard ISO/IEC 23009-1:2014

**Comment by broofa** [comment]
Please file this with the jshttp/mime-db project.  This type is defined in https://github.com/jshttp/mime-db/blob/master/src/custom-types.json#L20

**Comment by mruddy** [comment]
ok, thanks, did that https://github.com/jshttp/mime-db/issues/44
