### ISSUE TITLE
application/vnd.adobe.photoshop

### ISSUE THREAD

**Issue by kapouer** [broofa/node-mime#147]
Hi,
i just found [that file](https://moken.eda.sarl/uploads/d66ba03527690fb8a6abeeade486be41.jpg), saved by some photoshop mac version with a mime type set in exif data to
`application/vnd.adobe.photoshop`. Extension should be `psd`.

**Comment by broofa** [comment]
.jpg extension, file has image/jpeg mime-type... behaving as expected.  This module doesn't introspect files for type.  It only looks at extensions.

**Comment by kapouer** [comment]
Correct ! totally forgot about this.

**Comment by broofa** [comment]
btw, apologies for the... uhh... year + 1 day delay on this.  this lib isn't exactly my top priority.   I'm doing a bit of housekeeping today. :-)
