### ISSUE TITLE
Remove fs and path dependencies

### ISSUE THREAD

**Issue by Gentlee** [broofa/node-mime#152]
Because of using `fs` and `path` it doesn't work on react-native.

**Comment by pixelwhip** [comment]
Doh! I've been emptying out my node_modules directory and clearing caches over and over trying to figure out why this wasn't working. Then I saw the those require statements.

**Comment by pixelwhip** [comment]
https://github.com/eyaleizenberg/mimetype-js
Worked in React Native for my specific use-case.

**Comment by broofa** [comment]
fixed in 'v2'
