### ISSUE TITLE
Error while installing mime

### ISSUE THREAD

**Issue by himanshuphirke** [broofa/node-mime#153]
> npm ERR! Linux 4.4.0-66-generic
> npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.10.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.10.1/bin/npm" "install"
> npm ERR! node v6.10.1
> npm ERR! npm  v3.10.10
> npm ERR! path ../mime/cli.js
> npm ERR! code EROFS
> npm ERR! errno -30
> npm ERR! syscall symlink
> 
> npm ERR! rofs EROFS: read-only file system, symlink '../mime/cli.js' -> '/home/ubuntu/host/dev/mongo/hw1-3/node_modules/.bin/mime'
> npm ERR! rofs This is most likely not a problem with npm itself
> npm ERR! rofs and is related to the file system being read-only.
> npm ERR! rofs 
> npm ERR! rofs Often virtualized file systems, or other file systems
> npm ERR! rofs that don't support symlinks, give this error.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/host/dev/mongo/hw1-3/npm-debug.log
>

**Comment by broofa** [comment]
"related to the file system being read-only"

**Comment by himanshuphirke** [comment]
Please see this: https://github.com/npm/npm/issues/9901

I get the error when ~/host is a mounted partition. Also the this is running in a Virtual box machine
