### ISSUE TITLE
no longer able to override mimetype

### ISSUE THREAD

**Issue by hikirsch** [broofa/node-mime#157]
It seems in the last 1.3.5 push, there's a new continue when detecting an existing mime type thus no longer allowing to override the content type.
https://github.com/broofa/node-mime/blob/master/mime.js#L43

This is has been the solution for so long
https://github.com/angular/angular-cli/issues/2125#issuecomment-247395088

This breaks all of our builds right now and I would hope that this would break the semantic versioning of the project and would be consider to be a major change.

Can we please unpublish 1.3.5 from npm?

**Comment by hikirsch** [comment]
it seems for now i can specifically install version 1.3.4 in my package.json my karma tests will still run

**Comment by broofa** [comment]
Reverted facet commit (902ec070313fd40c9a8135ef4ef401f8a1db9472) and published as v1.3.6.  Deprecated v1.3.5.
