### ISSUE TITLE
woff and woff2

### ISSUE THREAD

**Issue by sbechet** [broofa/node-mime#168]
`"application/font-woff":["woff"],"application/font-woff2":["woff2"],`

is

`"font/woff":["woff"],"font/woff2":["woff2"],`

Proof example:

* `wget -v https://fonts.gstatic.com/s/roboto/v16/ek4gzZ-GeXAPcSbHtCeQI_esZW2xOQ-xsNqO47m55DA.woff2`

**Comment by sbechet** [comment]
[IANA media-types database](http://www.iana.org/assignments/media-types/media-types.xhtml) :

```
font-sfnt - DEPRECATED in favor of font/sfnt | application/font-sfnt | [Levantovsky][ISO-IEC JTC1][RFC8081]
font-woff - DEPRECATED in favor of font/woff | application/font-woff | [W3C][RFC8081]
```

AND

```
woff | font/woff | [RFC8081]
woff2 | font/woff2 | [RFC8081]
```

**Comment by broofa** [comment]
This is an issue with mime-db. Please report there.

https://github.com/jshttp/mime-db/blob/master/db.json#L385
