### ISSUE TITLE
MIME breaking with 'class' declaration as it is without 'use strict mode'

### ISSUE THREAD

**Issue by ryu047** [broofa/node-mime#170]
### MIME module is breaking at `class` declaration, as it is expecting `use strict mode`.

Error states:
```
class Mime {
^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by broofa** [comment]
Thanks, looking into it.  Can you give a bit more context for where you're seeing this?   Is this in the browser? Node?  What browser, what version?  What packager are you using?
