### ISSUE TITLE
Changelog for v2.0 does not mention breaking changes

### ISSUE THREAD

**Issue by nickcampbell18** [broofa/node-mime#171]
Hello,

We use [Dependabot](https://dependabot.com/) to help us keep our dependencies up to date. This means that we usually spend a bit of time looking at Github releases or changelogs to see if a change is safe.

Looking at [the changelog for v2.0](https://github.com/broofa/node-mime/blob/a52b627ec9b867e8ae6b8595309b343e7d070df0/CHANGELOG.md#v200-12092017), it doesn't mention any breaking changes, so we merged the upgrade, but of course it broke things unexpectedly 😄 

Might be worth adding [this section from the readme](https://github.com/broofa/node-mime/commit/f7a2f7475c44fa4df0e7b51790a8932c42fd4a58) to the changelog to help other users?

Thanks!

**Comment by broofa** [comment]
Sorry about that.  I've only just started to get serious about maintaining a changelog and haven't been diligent about creating issues for the significant changes.  (FWIW, I'm using `github-release-notes` to auto-generate `changelog.md`, so adding the readme notes is slightly more involved.)

**Comment by nickcampbell18** [comment]
Not a problem - thank you for the quick fix!
