### ISSUE TITLE
How it works in brownser ?

### ISSUE THREAD

**Issue by lqixv** [broofa/node-mime#176]
I create a html file:

`<html>`
`    <head>`
`        <title>Hello World</title>`
`		<script src="mime.lite.js"></script>`
`		<script>`
`		var mime = new Mime();`
`alert(mime.getType("json")); // etc.`

`</script>`
`    </head>`
`    <body>`
        
`    </body>`
`</html>`

when I open it in browser, it not works. Could you tell me how should I do ?

**Comment by broofa** [comment]
I'm not sure what "mime.lite.js" is, but if it's browser-ready version of `mime/lite` from the `wzrd.in` CDN, then you can just refer to the `mimelite` variable, like so: https://jsfiddle.net/z66dann5/

(And, my apologies, the instructions in the README had some mistakes which I've corrected)
