### ISSUE TITLE
need ES5 version ready in npm package

### ISSUE THREAD

**Issue by kerryChen95** [broofa/node-mime#179]
front-end developers usually configure bundler, like webpack, not to use babel to compile ES6+ codes inside node_modules directory, otherwise babel need to compile tons of codes and it's too slow.

so I hope node-mine provide ES5 version out from npm package by using [package.json `browser` field](https://github.com/defunctzombie/package-browser-field-spec) to hint bundler which module to use.

**Comment by broofa** [comment]
The legacy version works with ES5. `npm install mime@^1`
