### ISSUE TITLE
Update mime-db to 1.31.0 in v1.x branch

### ISSUE THREAD

**Issue by rhmoller** [broofa/node-mime#181]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

  [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
  [x] Yes: Go ahead and submit your issue/PR here and I'll look into it.

Please upgrade the mime-db dependency to 1.31.0 in the v1.x branch. This will add support for WebAssembly which is needed by webpack-dev-middleware. See https://github.com/webpack/webpack-dev-middleware/issues/229

**Comment by Janpot** [comment]
Looks like my problem in https://github.com/expressjs/express/issues/3486 would be solved too by backporting `mime-db` in `v1.x`.

**Comment by broofa** [comment]
Tagged & published v1.5.0, which is built on `mime-db@v1.31.0`

cc https://github.com/expressjs/express/issues/3486
