### ISSUE TITLE
Did 2.0.3 disappear from NPM?

### ISSUE THREAD

**Issue by dpjanes** [broofa/node-mime#184]
It's currently showing 1.6.0
https://www.npmjs.com/package/mime

**Comment by broofa** [comment]
No, it's still there.  However I published a maintenance version of the 1.x branch recently so technically that's what NPM thinks is 'latest'.  :-/  That seems wrong, though... let me see if I can straighten this out.

**Comment by broofa** [comment]
Okay, should be fixed.

For the record, 'just needed to do `npm dist-tag add mime@2.0.3 latest`

**Comment by broofa** [comment]
Thanks for reporting, btw.  Sorry for the inconvenience.

**Comment by dpjanes** [comment]
It blew my mind - time travel, backwards! Cheers.
