### ISSUE TITLE
.wasm missing from 2.x 

### ISSUE THREAD

**Issue by shellscape** [broofa/node-mime#185]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

 - [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
 - [x] Yes: Go ahead and submit your issue/PR here and I'll look into it.

It looks like the 1.x has enjoyed an update from mime-db which includes a definition for `.wasm' in this commit: https://github.com/broofa/node-mime/commit/c0853d2f600235c6019b57ce68f1d0845c9319b7

The relevant commit in mime-db is https://github.com/jshttp/mime-db/commit/1ab71a1d8a2c15be21b1f457e9109d49b48b91a3

The 2.x branch looks like it needs an update as well.

**Comment by broofa** [comment]
Thanks for the report.  I'll look into it.
