### ISSUE TITLE
Provide an API for sniffing mime types

### ISSUE THREAD

**Issue by deepakjois** [broofa/node-mime#191]
Would you consider adding support for the [MIME Sniffing Standard][mimesniff], and exposing an API for the same.

[mimesniff]: https://mimesniff.spec.whatwg.org/

A lot of packages use node-mime, esp Node-based web servers. But they server a file with no extension as `application/octet-stream` even if the content is HTML.

It would be nice to expose a way to do mime sniffing. Then it becomes possible to patch these servers upstream to all mime sniffing as an option.

**Comment by deepakjois** [comment]
Here is a concrete implementation of the algorithm specified in the MIME Sniffing Standard, which takes as input, the first 512 bytes of content from the resource, and returns a MIME type.

If you can provide some guidance regarding the API to expose, I will be happy to code it up myself.

**Comment by broofa** [comment]
I don't see this adding much value.  Both the code and the API would be completely distinct from what's already here.  I.e. this could/should just be implemented as a separate module.
