### ISSUE TITLE
Mp3 is defined twice causing an error

### ISSUE THREAD

**Issue by Tivoli** [broofa/node-mime#192]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

  [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
  [x] Yes: Go ahead and submit your issue/PR here and I'll look into it.

`mp3` is defined in both `audio/mp3` and `audio/mpeg` causing the following error:

`Error: Attempt to change mapping for "mp3" extension from "audio/mp3" to "audio/mpeg". Pass `force=true` to allow this, otherwise remove "mp3" from the list of extensions for "audio/mpeg".`

**Comment by broofa** [comment]
I'm not seeing it.  Please provide a recipe for reproducing.

**Comment by Tivoli** [comment]
Originally i was importing 'mime/lite', switching back to just 'mime' seems to have resolved the issue for me. Closing this unless I can find a valid reproducible bug.

**Comment by Baggz** [comment]
@Tivoli 

Having the same issue. Guess it's related to Webpack evaluating the `import 'mime/lite'` twice, causing it to import the db twice. Had to switch back to `import 'mime'` until I figure out how to fix it.

**Comment by caub** [comment]
Yes confirmed, since v2.2.2 [`"audio/mp3":["*mp3"],"audio/mp4":["m4a","mp4a"],"audio/mpeg":["mpga","mp2","mp2a","mp3","m2a","m3a"]`](https://github.com/broofa/node-mime/compare/v2.2.0...v2.2.2)

mp3 is there twice
```
/home/caub/dev/aula-assignment/packages/server/node_modules/mime/Mime.js:49
        throw new Error(
        ^

Error: Attempt to change mapping for "mp3" extension from "audio/mp3" to "audio/mpeg". Pass `force=true` to allow this, otherwise remove "mp3" from the list of extensions for "audio/mpeg".
    at Mime.define (/home/caub/dev/aula-assignment/packages/server/node_modules/mime/Mime.js:49:15)
```

It's not reproducible with a simple `const mime = require('mime/lite')` but it breaks bigger applications

**Comment by broofa** [comment]
@caub I need a recipe for reproducing this before I can reopen this issue.  I'm not seeing any obvious issues in the module itself.  (tests are passing, I'm able to require `mime` and `mime/lite` and lookup extensions and type w/out issue.)

**Comment by caub** [comment]
couldn't repeat this error, nevermind then

**Comment by caub** [comment]
I found why, we need to copy types/standard.json, either JSON.parse(JSON.stringify(require('./types/standard'))) or something better in both mime and lite

**Comment by broofa** [comment]
Yeah, `define()` is mutating it's `typeMap` args, which becomes a problem if the same map is used more than once.  I just put up a PR that fixes this.
