### ISSUE TITLE
why mime.getType('unknown') returns null rather then 'application/octet-stream'

### ISSUE THREAD

**Issue by xxoo** [broofa/node-mime#195]
according to https://tools.ietf.org/html/rfc2045
```
Any entity with an unrecognized Content-Transfer-Encoding must be
treated as if it has a Content-Type of "application/octet-stream",
regardless of what the Content-Type header field actually says.
```
as i understood a unknown file type should use application/octet-stream for sure.

**Comment by broofa** [comment]
This module is not an RFC-related module.  It's a thin, optimized API for the `mime-db` dataset.  That said, the previous version of this module had the behavior you described.  However, this behavior was deemed undesirable (see #139).

Basically, returning `null` is what most people expect, and it's trivial for callers of this API to code a default value.  E.g. `var type = mime.getType(...) || 'application/octet-stream';`.

**Comment by almercier** [comment]
@broofa This should have been documented as a breaking change...

**Comment by almercier** [comment]
@broofa This probably should have been documented as a breaking change as this broke our logic what was expecting the 'application/octet-stream' default return value.
