### ISSUE TITLE
Missing file extensions are breaking webpack-dev-middleware

### ISSUE THREAD

**Issue by scott-cornwell** [broofa/node-mime#197]
Doing hot reload of node server that runs webpack-dev-middleware. It depends on mime and in the index.js of mime it imports some json files in types with no extension. If I add the .json extension it works. Can these be added please?

**Comment by scott-cornwell** [comment]
Nevermind, it was my fault, I just needed to add `.json` to my webpack resolve.extensions.

**Comment by marlon360** [comment]
When using this module with an Angular CLI project, I got this error:
> ERROR in ./node_modules/mime/index.js
Module not found: Error: Can't resolve './types/other' in '/www/mime-type-ng/node_modules/mime'
ERROR in ./node_modules/mime/index.js
Module not found: Error: Can't resolve './types/standard' in '/www/mime-type-ng/node_modules/mime'

In Angular CLI project you cannot edit the webpack configuration to resolve `.json` extensions.
Is it possible to change this line:
`module.exports = new Mime(require('./types/standard'), require('./types/other'));`
to this:
`module.exports = new Mime(require('./types/standard.json'), require('./types/other.json'));`

**Comment by broofa** [comment]
@marlon360, then that's an issue with Angular or your Angular config.

The CommonJS spec explicitly says module identifiers [should not include an extension](http://wiki.commonjs.org/wiki/Modules/1.1#Module_Identifiers).  Node.js is [explicit about this](https://nodejs.org/api/modules.html#modules_all_together) as well.

**Comment by nevercast** [comment]
Ah, thanks @broofa, for a moment I thought this was an issue with mime. I've fixed my webpack 👍

**Comment by marlon360** [comment]
If you don't want to or not able to edit the Webpack configuration, you can install my wrapper: https://github.com/marlon360/mime-wrapper
