### ISSUE TITLE
Cannot find module './types/standard' from 'index.js'

### ISSUE THREAD

**Issue by alfredzh** [broofa/node-mime#206]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

  [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
  [ x ] Yes: Go ahead and submit your issue/PR here and I'll look into it.

Hello!
I'm use Jest and Sinon to test my node server!

When I run test, Jest throw 
`Cannot find module './types/standard' from 'index.js'`

So I changed my local source code 'node-mime/index.js' of mime module!
`module.exports = new Mime(require('./types/standard.json'), require('./types/other.json'));`

Then it works fine! Seems like node can't find this file without extension !
What's the problem!?
Thank You!

My node version is
v9.11.1 !

**Comment by alfredzh** [comment]
Sorry! It's problem of Jest! Closed!

**Comment by lukas-zech-software** [comment]
For anybody else stumbling over this, here is the jest issue with the solution how to solve this

https://github.com/facebook/jest/issues/1371#issuecomment-237744653
