### ISSUE TITLE
Please support angular cli or publish a browser packed package

### ISSUE THREAD

**Issue by kbirger** [broofa/node-mime#208]
Currently, Angular CLI doesn't let you customize the webpack config that it generates, making it effectively impossible (to my knowledge) to use it in a project which uses Angular CLI.

Please add support for this in whichever way you think would be best. It is possible that the simplest solution would be to publish a separate package with the wzrd.in version. 

----
### [2019-01-01] A note from broofa (the project maintainer)
**This is an issue with Angular, not with this project**.  I'm only leaving this comment open to make it more visible for people struggling with the same issue.

**Want to help?**  Go read https://github.com/angular/angular-cli/issues/5043#issuecomment-401926712 , and then add your thoughts there.  Unless/until someone from the Angular projects makes a compelling argument for why this isn't actually their issue, I won't be acting on this.

Until then, consider using https://github.com/marlon360/mime-wrapper to workaround this issue.

**Comment by broofa** [comment]
While I'm tempted to fix this just to silence the recurring complaints I get about this, I don't believe this is a `mime`-specific issue.  It's an Angular problem (see above reference).  Feel free to chime in on that issue.  In the mean time, use the mime-wrapper module?

**Comment by kbirger** [comment]
It seems like I misunderstood the problem when opening the issue. From looking at the mime-wrapper code, it seems that the whole issue is solved by adding '.json' to the require calls? 

While I recognize that this is a fault in the angular tooling, would it not be simpler, and still standards-compliant to simply call require with the appropriate extension? The format of those required files will not change without a new version of your package, so what's the harm in explicitly requiring json?

I will, in the meantime, do as you suggest and use the wrapper.

**Comment by marlon360** [comment]
Here is a wrapper ready for Angular CLI: https://github.com/marlon360/mime-wrapper

**Comment by omarsourour** [comment]
It really can be solved simply by adding the `.json` extension. I am currently having to use the mime-wrapper library, but that just means I am hoping you don't change any of your innards file organization.

**Comment by broofa** [comment]
@omarsourour See note I just added to description.

**Comment by broofa** [comment]
If someone wants to fixup `src/build.js` per [this comment](https://github.com/angular/angular-cli/issues/13576#issuecomment-459917132), I'd take a PR.

**Comment by marlon360** [comment]
I made a PR #226 with the necessary changes according to [this comment](https://github.com/angular/angular-cli/issues/13576#issuecomment-459917132).

**Comment by broofa** [comment]
Thanks for jumping on this, @marlon360.  Fix is up on npm as v2.4.3.  Let me know if you see any problems.

**Comment by ViceIce** [comment]
This is actually a breaking change, because you changed the package layout.

If I update to the new bugfix release it would break my build, because of the changed file extension.

**Comment by broofa** [comment]
@ViceIce While I sympathize, since this is not a change to the public API it does not constitute a breaking change. From https://semver.org/ (emphasis mine):

> Once you identify your ***public API***, you communicate changes to it with specific increments to your version number

**Comment by ViceIce** [comment]
Ok, i thought, the types json files were actually public api.
