### ISSUE TITLE
[bug] Module not found: Error: Can't resolve './types/other' in '\node_modules\mime'

### ISSUE THREAD

**Issue by pinghe** [broofa/node-mime#211]
ERROR in ./node_modules/mime/index.js
Module not found: Error: Can't resolve './types/other' in '\node_modules\mime'

In line 4 of index.js, the code needs to be modified to

```
module.exports = new Mime(require('./types/standard.json'), require('./types/other.json'));
```

Need to clear the file suffix is json。

my env:

yarn: 1.9.4
node:  9.6.1

**Comment by broofa** [comment]
See #197
