### ISSUE TITLE
Apparently, the preferred mime-type for javascript is changing...

### ISSUE THREAD

**Issue by getify** [broofa/node-mime#212]
In [this thread](https://github.com/webhintio/hint/issues/568), and more specifically [here](https://github.com/whatwg/mimesniff/issues/76#issuecomment-411662248), apparently the long-held preference of `application/javascript` is switching to `text/javascript`.

It would be appreciated if this utility would update accordingly.

**Comment by broofa** [comment]
Interesting.  Please file this with the https://github.com/jshttp/mime-db project.  That's where this module pulls it's MIME definitions from.

**Comment by samuelcolvin** [comment]
See https://github.com/jshttp/mime-db/issues/194.

**Comment by getify** [comment]
Just for clarification, does this package need to do anything extra to receive the now updated .js MIME type from the "mime-db" registry?

**Comment by broofa** [comment]
> Does this package need to do anything extra ...?

I do need to update the `mime-db` dependency when that changes, but the changes you're referring to in `mime-db` [have not been published yet](https://github.com/jshttp/mime-db/blob/913be07d867f91c95ddb4e4a29c70c4720f7b4ca/HISTORY.md#unreleased).

Ping me here when that happens and I'll push a new release.

cc @dougwilson (for update on when to expect a new release)

**Comment by getify** [comment]
> the changes you're referring to in mime-db have not been published yet

Ahhh, I just saw that [the issue tracking it had been closed](https://github.com/jshttp/mime-db/issues/266), but didn't realize that the release hadn't happened.

Since that issue was also locked, I don't expect it will get any more notifications when such a release happens. Hopefully @dougwilson can let us know here when it does. :)

**Comment by dougwilson** [comment]
Hi @broofa , I will let you know. I recently went to make a release, but found nvm is broken for our build. I opened an issue on nvm and the issue is fixed, but nvm has not yet made a release with the fix. I will get a new mime-db releaased as soon as that happens 👍
