### ISSUE TITLE
My OS/node combo (Android x86/node v6.5.0 in my case) don't like capital in filename

### ISSUE THREAD

**Issue by jefhil** [broofa/node-mime#215]
In index.js, my OS/node combination (Android x86/ node v6.5..0) doesn't like the captial
'M' the in require filename

var Mime = require('./Mime');

**Comment by broofa** [comment]
File is named `Mime.js` and is required as `./Mime.js`.  If your OS can't deal with capital letters in filenames, then this module is almost certainly the least of your problems.

Provide an SSCCE + details about what is causing the problem and I may consider reopening.

**Comment by jefhil** [comment]
sorry to have bothered you -- my filename somehow got lowercased
________________________________
