### ISSUE TITLE
A bizarrerie url will return null by method getType().

### ISSUE THREAD

**Issue by su-chang** [broofa/node-mime#235]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

- [x] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
- [ ] Yes: Go ahead and submit your issue/PR here and I'll look into it.

### Example
```js
mime.getType('https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5d0231f2b847d96f9cdfdae1_1587716279293_null') // return null
```
This url will return null by getType().

Do you have some good idea about process this kind of url?

**Comment by broofa** [comment]
This module is not designed to extract type information from a URL endpoint (e.g. by fetching the URL and inspecting headers).  It is strictly for inferring type from a file name (specifically, a file extension).

Most URLs will provide a `Content-Type` header which will be made available by whatever API module you use to make the request.  If you need to know the type prior to fetching the URL, you can make a HEAD request.  E.g. `request.head()`, `axios.head()`.  Or for a one-off occurance you can do this using `curl` from the command line:
```
$ curl -I "https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/5d0231f2b847d96f9cdfdae1_1587716279293_null"
HTTP/1.1 200 OK
x-amz-id-2: uvMK24y/0EYSCIzAegqN14LFflHYJJ9pI70IWGd/WiBd7dDlbwoDIeE38b8rSSYfu0Rf18gNb8c=
x-amz-request-id: 44B2F7E2B31F51AA
Date: Fri, 24 Apr 2020 16:50:20 GMT
Last-Modified: Fri, 24 Apr 2020 08:18:00 GMT
ETag: "fdac0d8bfcc3ea1bda5337d0802260e4"
Accept-Ranges: bytes
Content-Type: image/png
Content-Length: 11576
Server: AmazonS3
```

**Comment by su-chang** [comment]
Thanks for your professional answer.
