### ISSUE TITLE
Consider making the `Requesting New Types` information more visible

### ISSUE THREAD

**Issue by alrra** [broofa/node-mime#77]
Most of the [recent pull requests](https://github.com/broofa/node-mime/search?q=https%3A%2F%2Fgithub.com%2Fbroofa%2Fnode-mime%2Fwiki%2FRequesting-New-Types&ref=cmdform&type=Issues) contained commits that tried to change the `mime.types` file instead of `node.types`. 

I suspect this is because the majority of people don't read wikis and few ever read the `README.md` carefully (thus not seeing / following the [_"requesting new types"_ link](https://github.com/broofa/node-mime/wiki/Requesting-New-Types) to the wiki).

So, I think it would be better to just move the information from the `wiki` somewhere where it can be immediately visible, like, for example, in the [`README.md`](https://github.com/broofa/node-mime/blob/master/README.md) or maybe into a  [`CONTRIBUTING.md`](https://github.com/blog/1184-contributing-guidelines) file.

**Comment by broofa** [comment]
node-mime now sits on top of https://github.com/jshttp/mime-db.  (i.e. this project is no longer in the business of managing custom mime extensions.)
