### ISSUE TITLE
don't make default_type global

### ISSUE THREAD

**Issue by jonathanong** [broofa/node-mime#78]
i'd prefer when a lookup fails, it returns something falsey like `false` instead of `application/octet-stream`. i would love to set the default type to something, but since it's global, i'm afraid it'll ruin other modules since this repo is used a lot.

aside from doing a major version bump, how about adding a second "default" option to the methods?

``` js
mime.lookup(file, false)
```

would return a valid mime type or `false`

**Comment by jons** [comment]
when in doubt, do what the standard says, or in this case, do what the most common tools do.

http://linux.die.net/man/1/file
http://linux.die.net/man/5/magic

**Comment by broofa** [comment]
See #139 (plan is to have v2 return null instead of default type.)
