### ISSUE TITLE
Add mime type for Opus audio files

### ISSUE THREAD

**Issue by jonkoops** [broofa/node-mime#94]
Currently there is no mime-type available for Opus audio. Would it be possible to add the `audio/ogg; codecs=opus` mime-type for files using a `.opus` extension?

For more info see the [Opus documentation](http://wiki.xiph.org/OggOpus#Content_Type).

**Comment by broofa** [comment]
node-mime now sits on top of https://github.com/jshttp/mime-db.  Please submit requests for new types there.  Thanks!
